version: '3.9'
services:
  serverDB:
    image: postgis/postgis:15-3.3-alpine
    container_name: serverDB
    restart: always
    environment:
      - POSTGRES_DB=TrackingOrders
      - POSTGRES_USER=AdminDB
      - POSTGRES_PASSWORD=WC18122023
    volumes:
      - /var/lib/postgresql/data     
    ports:
      - 5432:5432
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@TrackingOrders.edu
      - PGADMIN_DEFAULT_PASSWORD=tesina2023
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8081:80
    volumes:
      - /var/lib/pgadmin  
    depends_on:
      - serverDB

  app-back:
    image: orders-tracking-back:latest
    container_name: ms1 
    restart: always
    ports:
      - 8085:8085
    depends_on:
      - serverDB

  proxy-server-web:
    image: orders-tracking-web
    container_name: orders-tracking-front
    restart: always
    ports:
      - 80:80
    depends_on:
      - pgadmin
      - app-back
                   